spring:
  profiles:
    active: english,dog,prod
test:
  username: YmlUsername
  password: YmlPassword
  jdbcUrl: YmlJdbcUrl

---
spring:
  profiles: prod
test:
  username: ProdYmlUsername
  password: ProdYmlPassword
  jdbcUrl: ProdYmlJdbcUrl